
[build]
  command = "npm run build"  
  publish = "dist"        

# Redirects 
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"  
  status = 200  

# Headers 
[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"
